Registration window
kpdchat/kpdchat pull request #2
Opened 2023-07-27 13:15 UTC by vlaskiri

2023-08-02 18:56 UTC, mtjal reviewed
Everything but minor style issues seems fine to me

2023-08-02 18:56 UTC, mtjal commented on .gitignore
> +.idea
It seems this line don't work, try to look into this: https://stackoverflow.com/questions/32384473/gitignore-not-ignoring-idea-path

2023-08-02 18:56 UTC, mtjal commented on src/App.test.js
> +  expect(test).toBe(test);
I don't know how JS works but make sure there is no recursion here

2023-08-02 18:56 UTC, mtjal commented on src/components/registrationWindow/Registration/RegistrationInput.jsx
> +
Wasn't empty lines left here by accident?

2023-08-02 18:56 UTC, mtjal commented on src/styles/RegistrationWindow/modal.scss
> +    // .modal__content-columnLine
I suppose tabulation is missing here

2023-08-02 18:56 UTC, mtjal commented on src/styles/RegistrationWindow/template.scss
> +$fontF3: 'Montserrat', sans-serif;
Consider replacing shortenings with full words in font variables

2023-08-02 18:56 UTC, mtjal commented on src/styles/index.scss
> +  //overflow: hidden;
It's better not to leave commented-out code

2023-08-03 09:55 UTC, vlaskiri commented on .gitignore
> +.idea
What makes you think it doesn't work? It's added to .gitignore and should work as expected. I don't understand what is the problem?

2023-08-03 09:57 UTC, vlaskiri commented on src/App.test.js
> +  expect(test).toBe(test);
We put a stub on the tests so that it does not give errors during testing. The code is working correctly.

2023-08-03 10:00 UTC, mtjal commented on .gitignore
> +.idea
Here https://github.com/kpdchat/kpdchat/tree/registration-window you can see all the branch files and `.idea` directory is among them. Also in [changes list](https://github.com/kpdchat/kpdchat/pull/2/files) you can see added files like `.idea/modules.xml`.

2023-08-03 10:01 UTC, vlaskiri commented on src/components/registrationWindow/Registration/RegistrationInput.jsx
> +
Empty lines do not affect the operation of the site in any way; the browser does not read them in any way. This was done during the implementation of the modal window. This code will still be improved, and only by me, so I left it like that for now. If there is an urgent need, I will remove the extra spaces.

2023-08-03 10:05 UTC, mtjal commented on src/components/registrationWindow/Registration/RegistrationInput.jsx
> +
There is no any urgency in removing extra spaces, I just commented on what I have noticed as it can be easily changed in among other changes to the PR, if there will be any.

2023-08-03 10:06 UTC, vlaskiri commented on src/styles/RegistrationWindow/modal.scss
> +    // .modal__content-columnLine
<img width="322" alt="Снимок экрана 2023-08-03 в 1 03 01 PM" src="https://github.com/kpdchat/kpdchat/assets/104367862/359c64ef-24fa-4080-bc0e-c661418f41e9">


Everything is present here according to the scss preprocessor policy
The comment was left so that the style could be found by searching in the code editor.

2023-08-03 10:10 UTC, mtjal commented on src/styles/RegistrationWindow/modal.scss
> +    // .modal__content-columnLine
I mean, shouldn't it be
```
    &-columnLine {
      // .modal__content-columnLine
      width: 100%;
      height: 1px;
      background: rgba(171, 168, 212, 0.25);
      margin: 40px 0 28px 0;
    }
  }
```
instead of
```
    &-columnLine {
    // .modal__content-columnLine
    width: 100%;
    height: 1px;
    background: rgba(171, 168, 212, 0.25);
    margin: 40px 0 28px 0;
  }
  }
```
?

2023-08-03 10:16 UTC, vlaskiri commented on .gitignore
> +.idea
The issue is resolved, the folder is no longer in the repository, it is locally in the project.

2023-08-03 10:17 UTC, vlaskiri commented on src/components/registrationWindow/Registration/RegistrationInput.jsx
> +
Fine. I left the spaces on purpose, in the future I will add and change the code, and for this I need space for reflection)

2023-08-03 10:20 UTC, mtjal commented on src/components/registrationWindow/Registration/RegistrationInput.jsx
> +
Consider using `// TODO: ...` comments

2023-08-03 10:21 UTC, vlaskiri commented on src/styles/RegistrationWindow/modal.scss
> +    // .modal__content-columnLine
No, it's just a line that is part of a column

![Снимок экрана 2023-08-03 в 1 20 10 PM](https://github.com/kpdchat/kpdchat/assets/104367862/d36d2a03-1253-4fdb-92cc-3f3f6263ef8e)

2023-08-03 10:22 UTC, vlaskiri commented on src/styles/RegistrationWindow/template.scss
> +$fontF3: 'Montserrat', sans-serif;
This is a draft version of the variables. When merging our branches, we will resolve the conflict with the name of the variables, since Lisa also has her own variables

2023-08-03 10:27 UTC, vlaskiri commented on src/styles/index.scss
> +  //overflow: hidden;
Done )

2023-08-05 13:05 UTC, elzbthbrst submitted a review, later dismissed

2023-08-05 15:27 UTC, mtjal approved these changes
Good work at improving and generalizing code style.

2023-08-05 15:27 UTC, mtjal commented on src/components/chatWindow/messages/MessageItem.jsx
> +//here u should create 3 components self-message | another-message | data
Such instructions in code better start with `// TODO:` so it can be found easier later

2023-08-05 15:27 UTC, mtjal commented on src/components/chatWindow/WindowChat.jsx
> +            {/* <div className='chat'> */ }
Is this commented-out code left here by purpose or accidentally?

2023-08-05 15:29 UTC, vlaskiri commented on src/components/chatWindow/WindowChat.jsx
> +            {/* <div className='chat'> */ }
intentionally

2023-08-05 15:30 UTC, vlaskiri commented on src/components/chatWindow/messages/MessageItem.jsx
> +//here u should create 3 components self-message | another-message | data
Will fix after conflicts are resolved

2023-08-05 19:33 UTC, elzbthbrst approved these changes

2023-08-05 22:52 UTC, mtjal requested changes
I figured out how to do the rebase, don't merge yet.

2023-08-06 08:20 UTC, mtjal approved these changes

2023-08-06 08:31 UTC, merged